services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 myproject.myproject.asgi:application
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
